site_name: 'プログラミング言語 Mokkosu'
repo_url: https://github.com/lambdataro/Mokkosu
theme: Bootstrap
pages:
- ['index.md', 'トップ']
- ['start.md', '始め方']
- ['tutorial/part01.md', 'チュートリアル', 'パート1']
- ['reference/basic.md', 'リファレンスマニュアル', '基本事項']
- ['reference/statement.md', 'リファレンスマニュアル', '文']
- ['reference/type.md', 'リファレンスマニュアル', '型とリテラル']
- ['reference/expression.md', 'リファレンスマニュアル', '式']
- ['reference/dotnet.md', 'リファレンスマニュアル', '.NET関連の式']
- ['reference/pattern.md', 'リファレンスマニュアル', 'パターン']
- ['sample.md', 'サンプル']
