site_name: 'プログラミング言語 Mokkosu'
repo_url: https://github.com/lambdataro/Mokkosu
theme: Bootstrap
pages:
- ['index.md', 'トップ']
- ['start.md', '始め方']
- ['tutorial/part01.md', 'チュートリアル', 'パート1']
- ['langmanual.md', '言語']
- ['libmanual.md', 'ライブラリ']
- ['sample.md', 'サンプル']